### ISSUE TITLE
Issue with version 24.3.2 and above

### ISSUE THREAD

**Issue by paskovitch** [AuxXxilium/arc#920]
Hello!
I'm running ARCLoader on a Dell R210 II server. Has there been any significant structural change since version 24.3.2? My server only boots with this version; larger versions do not work. I've updated the loader, the server starts up, gets an IP, but after 30 minutes, it still doesn't load. 
During the Loader installation, it displays a message stating that the CPU does not support virtualization technology, even though it does, and it's enabled in the BIOS. Nevertheless, I can still run a VM under DSM. I also can't monitor the status of the HDDs under Scrutiny, this worked with older loader versions. What could be the problem?

Sysinfo code: 
6M9NBA6JQ

Thanks!

**Comment by AuxXxilium** [comment]
Use latest and try again.

BTW: i don't know why you select nearly every addon. don't think you need all. and nvme cache and storage together can cause issues while boot, because you can't use the same ssd as storage and as cache, and if you select storage, you don't need to select cache. And the description is clear: "Enable M2 as cache device (for non supported Models)" <- for non supported models, 3622 supports nvme cache.

there are many things, that tell me you havn't read the wiki and the messages inside loader.

to kvm message: the loader checks for vmx support by cpu, if it is not active, the message appear, because not all os will run in vmm without this!
